# Generated by Django 3.1.3 on 2024-06-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20240603_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postImage',
            field=models.TextField(null=True),
        ),
    ]
