# Generated by Django 3.1.3 on 2024-06-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.TextField(default='https://th.bing.com/th/id/R.da23698789163cd86b5926cb55febc91?rik=lQ3tuFTKGq8YTw&riu=http%3a%2f%2fgetdrawings.com%2fimage%2fcute-cactus-drawing-56.jpg&ehk=yCYuKpvbrcGogPfx5fF6miInOgx1qmTSwHOu3%2fqYUgg%3d&risl=&pid=ImgRaw&r=0'),
        ),
    ]
