# Generated by Django 3.1.3 on 2024-05-31 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type', models.TextField()),
                ('origin', models.TextField()),
                ('description', models.TextField()),
                ('image', models.TextField()),
            ],
        ),
    ]
