# Generated by Django 3.1.3 on 2024-06-01 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_auto_20240601_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='description',
            new_name='plantDescription',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='image',
            new_name='plantImage',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='name',
            new_name='plantName',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='origin',
            new_name='plantOrigin',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='type_plant',
            new_name='plantType',
        ),
    ]
