# Generated by Django 3.1.3 on 2024-06-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameName', models.TextField()),
                ('gameDescription', models.TextField()),
                ('gameIcon', models.TextField()),
                ('gameImage', models.TextField()),
            ],
        ),
    ]
